version: '3.8'

networks:
  loft-network:

volumes:
  loft-mysql-data:

services:
  nginx:
    image: nginx:1.22-alpine
    ports:
      - "80:80"
    volumes:
      - ../src:/var/www/html:delegated
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - loft-network
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: development.Dockerfile
    volumes:
      - ../src:/var/www/html:delegated
    environment:
      XDEBUG_MODE: "${XDEBUG_MODE-off}"
      XDEBUG_CONFIG: 'start_with_request=yes client_host=${XDEBUG_CONFIG_CLIENT_HOST-} idekey=${XDEBUG_CONFIG_IDEKEY-}'
    depends_on:
      - mysql
    networks:
      - loft-network

  mysql:
    image: mysql:latest
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - loft-mysql-data:/var/lib/mysql:delegated
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - loft-network