<?php //= $error;?>

<h4 style="margin-bottom: 2px">Регистрация</h4>:
<form action="/user/register" method="post">
    <label style="display: flex; flex-direction: column; width: 200px;">
        <span>Имя:</span>
        <input type="text" name="name">
    </label> <br>
    <label style="display: flex; flex-direction: column; width: 200px;">
        <span>Пароль: </span>
        <input type="password" name="password">
    </label> <br>
    <button style="width: 160px; background: skyblue; border: none; color: white; padding: 6px 12px; border-radius: 10px" type="submit">Зарегистрироваться</button>
</form>
<br>
<br>

<h4 style="margin-bottom: 2px">Войти</h4>
<form action="/user/login" method="post">
    <label style="display: flex; flex-direction: column; width: 200px;">
        <span>Имя: </span>
        <input type="text" name="name">
    </label> <br>
    <label style="display: flex; flex-direction: column; width: 200px;">
        <span>Пароль: </span>
        <input type="password" name="password">
    </label> <br>
    <button style="width: 160px; background: skyblue; border: none; color: white; padding: 6px 12px; border-radius: 10px" type="submit">Войти</button>
</form>

<br>
<br>
<?php if($this->error): ?>
    <span style="color: red"><?=$this->error;?></span>
<?php endif; ?>
